### ISSUE TITLE
Cricket background and tilemap

### ISSUE THREAD

**Issue by abalidoth** [abalidoth/get-in-the-cricket-shinji#7]
Create background image for the cricket. (Do we want a separate background for the ground underneath? Maybe have it move when the cricket does, for a little extra verisimilitude?)

**Comment by clermorgaine** [comment]
Ok, we have a placeholder background, but it is too pretty! we need one that looks grosser (and more importantly, distracts less from the hex grid on top of it)

**Comment by clermorgaine** [comment]
Done!
